#!/bin/sh

EX4SYSTEMDTIMER=$1

# skip in favour of systemd timer if called from cron.daily
if [ -d /run/systemd/system ] && [ "$EX4SYSTEMDTIMER" != "systemd-timer" ]; then
    exit 0
fi

[ -f /usr/bin/apt-show-versions ] || exit 0

apt-show-versions -i
